<?php

//URL dan nama aplikasi
$link="http://localhost/project_co_id/news/";
$nama_aplikasi="UII";
$tahun_aplikasi="2018";
$logo_aplikasi="Logo-Stmik-Crop.png";
$timeload=1550;


//Konfigurasi DB

$hostname_pam = "localhost";
$database_pam = "dppaiui_penilaian";
$username_pam = "root";
$password_pam = "";
function dtb(){
$hostname_pam = "localhost";
$database_pam = "dppaiui_penilaian";
$username_pam = "root";
$password_pam = "";
//Koneksi Database mamen
mysql_connect("$hostname_pam", "$username_pam", "$password_pam")or die("Koneksi Gagal");
mysql_select_db("$database_pam")or die("Koneksi Database Gatot bro");

}

$pam = mysql_pconnect($hostname_pam, $username_pam, $password_pam) or trigger_error(mysql_error(),E_USER_ERROR); 

$conn = mysqli_connect($hostname_pam, $username_pam, $password_pam, $database_pam) or die("Connection failed: " . mysqli_connect_error());



$anilai=80;
$bnilai=70;
$cnilai=60;
$dnilai=50;

function buatrp($angka){
	$jadi = "Rp " . number_format($angka,2,',','.');
	return $jadi;
}
/* Nama File : b_konek.php*/
/* Generated by Pampam CMS Generator pada tanggal 07-05-2016 02:47:41 */
?>